In [1]:
import pandas as pd

In [20]:
df = pd.read_csv('test.csv')
df=df.loc[:, ~df.columns.str.contains('^Unnamed')]
df.head()

,original_title,Director,Combined,overview
0,Avatar,James Cameron,"Sam Worthington,Zoe Saldana,Sigourney Weaver,J...","In the 22nd century, a paraplegic Marine is di..."
1,Pirates of the Caribbean: At World's End,Gore Verbinski,"Johnny Depp,Orlando Bloom,Keira Knightley,Gore...","Captain Barbossa, long believed to be dead, ha..."
2,Spectre,Sam Mendes,"Daniel Craig,Christoph Waltz,Léa Seydoux,Sam M...",A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,Christopher Nolan,"Christian Bale,Michael Caine,Gary Oldman,Chris...",Following the death of District Attorney Harve...
4,John Carter,Andrew Stanton,"Taylor Kitsch,Lynn Collins,Samantha Morton,And...","John Carter is a war-weary, former military ca..."

In [4]:
df.to_hdf('test.h5','df',complevel=1,complib='bzip2')

In [5]:
df.to_csv('test.txt')

In [21]:
df.to_csv('test.bz', compression='bz2')

In [9]:
df.to_pickle('test1.pkl')

In [8]:
df1.head()

,Unnamed: 0,original_title,Director,Combined,overview
0,0,Avatar,James Cameron,"Sam Worthington,Zoe Saldana,Sigourney Weaver,J...","In the 22nd century, a paraplegic Marine is di..."
1,1,Pirates of the Caribbean: At World's End,Gore Verbinski,"Johnny Depp,Orlando Bloom,Keira Knightley,Gore...","Captain Barbossa, long believed to be dead, ha..."
2,2,Spectre,Sam Mendes,"Daniel Craig,Christoph Waltz,Léa Seydoux,Sam M...",A cryptic message from Bond’s past sends him o...
3,3,The Dark Knight Rises,Christopher Nolan,"Christian Bale,Michael Caine,Gary Oldman,Chris...",Following the death of District Attorney Harve...
4,4,John Carter,Andrew Stanton,"Taylor Kitsch,Lynn Collins,Samantha Morton,And...","John Carter is a war-weary, former military ca..."

In [19]:
df2=pd.read_csv('test.bz', compression='bz2')
df.head()

,original_title,Director,Combined,overview
0,Avatar,James Cameron,"Sam Worthington,Zoe Saldana,Sigourney Weaver,J...","In the 22nd century, a paraplegic Marine is di..."
1,Pirates of the Caribbean: At World's End,Gore Verbinski,"Johnny Depp,Orlando Bloom,Keira Knightley,Gore...","Captain Barbossa, long believed to be dead, ha..."
2,Spectre,Sam Mendes,"Daniel Craig,Christoph Waltz,Léa Seydoux,Sam M...",A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,Christopher Nolan,"Christian Bale,Michael Caine,Gary Oldman,Chris...",Following the death of District Attorney Harve...
4,John Carter,Andrew Stanton,"Taylor Kitsch,Lynn Collins,Samantha Morton,And...","John Carter is a war-weary, former military ca..."